language: cpp
compiler:
 - gcc
script:
 - make
 - ./main

before_install:
 - sudo apt-get install liblapack-dev

os:
 - linux

notifications:
  email:
    recipients:
      - zheng.wang.rice@gmail.com
    on_success: [never]
    on_failure: [always]